#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Thu Aug 15 21:09:17 2013

import datetime
import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade

class EventTable(wx.grid.PyGridTableBase):
  
    def GetNumberRows(self):
        """Return the number of rows in the grid"""
        return len(self.events)

    def GetNumberCols(self):
        """Return the number of columns in the grid"""
        return 2

    def IsEmptyCell(self, row, col):
        """Return True if the cell is empty"""
        return False

    def GetTypeName(self, row, col):
        """Return the name of the data type of the value in the cell"""
        return None

    def GetValue(self, row, col):
        """Return the value of a cell"""
        if col == 0:
            return str(self.events[row].startDate)
        else: 
            return self.events[row].content

    def SetValue(self, row, col, value):
        """Set the value of a cell"""
        pass

class MyFrame(wx.Frame):
    def __init__(self, model, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.ScrolledWindow(self, -1, style=wx.TAB_TRAVERSAL)
        self.grid_1 = wx.grid.Grid(self.panel_1, -1, size=(1, 1))
        self.button_1 = wx.Button(self, -1, "<")
        self.button_2 = wx.Button(self, -1, ">")
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/pb/Documents/dev/python/lifeHistory/wxglade/sample.JPG", wx.BITMAP_TYPE_ANY))

        self.__set_properties(model)
        self.__do_layout()
        # end wxGlade

    def __set_properties(self, model):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.grid_1.CreateGrid(3, 2)
        self.grid_1.SetRowLabelSize(0)
        self.grid_1.SetColLabelSize(0)
        self.grid_1.EnableEditing(0)
        self.grid_1.EnableGridLines(0)
        self.grid_1.EnableDragColSize(0)
        self.grid_1.EnableDragRowSize(0)
        self.panel_1.SetScrollRate(10, 10)
        # end wxGlade
        events = model.getEventsForDate(datetime.date.today())
        eventTable = EventTable()
        eventTable.events = events['text']
        self.grid_1.SetTable(eventTable)
        
    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.grid_1, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_1)
        sizer_3.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_4.Add(self.button_1, 0, 0, 0)
        sizer_4.Add(self.button_2, 0, 0, 0)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_3.Add(self.bitmap_1, 0, 0, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade
        width = self.grid_1.GetClientSize().GetWidth() - self.grid_1.GetColSize(0)
        #print width
        self.grid_1.SetColSize(1, width - 15)

# end of class MyFrame