#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Thu Aug 15 18:42:27 2013

import wx

# begin wxGlade: extracode
# end wxGlade


class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.ScrolledWindow(self, -1, style=wx.TAB_TRAVERSAL)
        self.label_11 = wx.StaticText(self.panel_1, -1, "2013-08-01")
        self.label_12 = wx.StaticText(self.panel_1, -1, "2013-08-02")
        self.label_13 = wx.StaticText(self.panel_1, -1, "2013-08-03")
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/pb/Documents/dev/python/lifeHistory/wxglade/sample.JPG", wx.BITMAP_TYPE_ANY))
        self.button_2 = wx.Button(self, -1, "<")
        self.button_3 = wx.Button(self, -1, ">")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("frame_2")
        self.panel_1.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(2, 1, 0, 0)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_3 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_3.Add(self.label_11, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_3.Add(self.label_12, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_3.Add(self.label_13, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5)
        self.panel_1.SetSizer(grid_sizer_3)
        grid_sizer_3.AddGrowableRow(0)
        grid_sizer_3.AddGrowableRow(1)
        grid_sizer_3.AddGrowableRow(2)
        grid_sizer_3.AddGrowableCol(1)
        grid_sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.bitmap_1, 0, wx.EXPAND | wx.SHAPED, 0)
        sizer_5.Add(self.button_2, 0, 0, 0)
        sizer_5.Add(self.button_3, 0, 0, 0)
        grid_sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_2.AddGrowableCol(0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        grid_sizer_1.AddGrowableCol(0)
        sizer_4.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame1
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_2 = MyFrame1(None, -1, "")
    app.SetTopWindow(frame_2)
    frame_2.Show()
    app.MainLoop()
